code --install-extension alefragnani.project-manager
code --install-extension andyyaldoo.vscode-json
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension eg2.tslint
code --install-extension esbenp.prettier-vscode
code --install-extension GrapeCity.gc-excelviewer
code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
code --install-extension ms-python.python
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension PeterJausovec.vscode-docker
code --install-extension redhat.vscode-yaml
code --install-extension vscode-icons-team.vscode-icons
code --install-extension vsmobile.vscode-react-native
code --install-extension zxh404.vscode-proto3
code --install-extension zhuangtongfa.Material-theme
code --install-extension coenraads.bracket-pair-colorizer-2
